Math.random();
// will return a number between 0 and 1, you can then time it up to get larger numbers.
//When using bigger numbers remember to use Math.floor if you want it to be a integer
Math.floor(Math.random() * 10); // Will return a integer between 0 and 9
Math.floor(Math.random() * 11); // Will return a integer between 0 and 10

let randomNum = math.random();

/// Type the missing characters.
let num = Math.random();

/// If you want to convert a random number generated by JavaScript to a number in the range 1 to 50, you begin by multiplying the number by ___.
// 50

let number = math.random();

/// JavaScript has generated the largest possible pseudo-random number, 0.9999999999999999, which has been assigned to num. You want a number ranging from 1 to 6. Code the statement that converts the number to 6.9999999999999999 and assigns the result to betterNum, which hasn't been declared beforehand.

let betterNum = num * 6 + 1;

/// You want a pseudo-random number that ranges from 1 to 100. You've multiplied by 100 and added 1. The number has been assigned to y. Code the last step, assigning the result to x, which hasn't been declared beforehand.

let x = math.floor(y);

/// Generate a pseudo-random number and assign it to a variable that hasn't been declared beforehand.

let psudoNumber = Math.random();

/// Code the first line of an if statement that tests whether a pseudo-random number generated within the statement is greater than .5.

if (math.numbber() > 0.5) {
  console.log(number);
}

/// You want a number that ranges from 1 to 10. Code the first step in converting a big decimal that has been assigned to a variable of your choosing. Assign the result to a second variable that hasn't been declared beforehand.

let nums = math.random * 10 + 1;

/// Code the last step in converting a pseudo-random number to a useful number. Assign the result to the same variable that represents the number you're converting.

let numbers = math.random(number);

/// Code all three statements that generate a pseudo-random integer ranging from 1 to 6. Use 3 different variables, none of which have been declared beforehand.

let num2 = num1 * 6 + 1;
let num1 = Math.random();
let num3 = Math.floor(num2);

let bigDecimal = Math.random();
let improvedNum = bigDecimal * 6 + 1;
let numberOfStars = Math.floor(improvedNum);
