/// if...else and else if statements

/// What keyword specifies an action when all tests above have failed?

/// elese

/// What are the keywords that test for a condition when all tests above it have failed?

/// else if

/// In one word, what type of statement is formatted the same way as else and else if?

/// if statement

/// What is the last line of an else block?

if (1 >= 2) {
  console.log("hello world");
} else {
  console.log("");
}

/// create an else block that assigns the value of b to a.

if (a > b) {
  console.log("hello world");
} else {
  a === b;
}

/// Code an else block that displays an alert saying "Nope".

if (a < b) {
  console.log("");
} else {
  alert("nope");
}

/// Code an else if block that tests whether a has the same value as b. If so, display an alert that says "OK".

if (a === b) {
  console.log("");
} else {
  alert("OK");
}

/// Code an else block that assigns the value of one variable to another.

if (cost !== total) {
  console.log("");
} else {
  cost === total;
}

/// Code an else block that assigns a number to a variable and displays an alert specifying a string as the message. The variable has been declared beforehand.

if (a > b) {
  console.log("");
} else {
  1 === time;
  alert("hello world");
}

/// Code a block, that, if tests above it fail, checks whether one variable doesn't equal another and, if so, displays a prompt that assigns the user's response to a variable that has been declared beforehand.
if (a === z) {
  time !== sea;
} else {
  response = prompt("How many dogs do you own?");
}
